name: Build artifacts

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: build seamstress
        run: |
          bash ci/ubuntu.sh
      - name: zip artifact
        run: |
          cd zig-out/ && tar -czvf ../seamstress-linux-x86_64-${{ github.ref_name }}.tar.gz .
      - uses: actions/upload-artifact@v2
        with:
          name: linux-x86_64-${{ github.ref_name }}
          path: |
            ./*.tar.gz
  macos-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: build seamstress
        run: |
          bash ci/macos-11.sh
      - name: zip artifact
        run: |
          cd zig-out/ && zip -r9 ../seamstress-macos-x86_64-${{ github.ref_name }}.zip .
      - uses: actions/upload-artifact@v2
        with:
          name: macos-x86_64-${{ github.ref_name }}
          path: |
            ./*.zip
  release:
    runs-on: ubuntu-latest
    needs: [macos-x86_64,linux-x86_64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            ./macos-x86_64-${{ github.ref_name }}/*.zip
            ./linux-x86_64-${{ github.ref_name }}/*.tar.gz
